//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSOpsExceptionServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adt.com/MasterMind/WebService/", ConfigurationName="ExceptionServiceReference.JobServiceSoap")]
    public interface JobServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/GetJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job> GetJobAsync(long Job_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/GetJobList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetJobListAsync(long[] job_NoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/GetActiveJobListForSite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetActiveJobListForSiteAsync(long site_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/GetActiveJobList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetActiveJobListAsync(long[] site_NoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/UpdateJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> UpdateJobAsync(TSOpsExceptionServiceReference.Job job, long emp_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/CancelJobBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfInt64> CancelJobBookingAsync(long job_No, long emp_No, string recall_Id, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/CancelJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfInt64> CancelJobAsync(long job_No, long emp_No, string recall_Id, string jobCause_Id, string jobRes_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/GetJobScheduledArrivalDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfDateTime> GetJobScheduledArrivalDateAsync(long job_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/TouchJobHeader", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfBoolean> TouchJobHeaderAsync(long jobNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adt.com/MasterMind/WebService/UpdateEstimatedHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfBoolean> UpdateEstimatedHoursAsync(long jobNumber, decimal estHours);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adt.com/MasterMind/WebService/")]
    public partial class Job
    {
        
        private long jOB_NOField;
        
        private System.DateTime cREATE_DATEField;
        
        private long cREATE_USERField;
        
        private long cO_NOField;
        
        private string jOBTYPE_IDField;
        
        private string jOBSTAT_IDField;
        
        private string iNSTALL_FLAGField;
        
        private string bILL_LABOR_FLAGField;
        
        private string bILL_PARTS_FLAGField;
        
        private string bILL_TRIP_FLAGField;
        
        private string lOCAL_FLAGField;
        
        private decimal eST_HOURSField;
        
        private decimal eXTRA_EQUIP_HOURSField;
        
        private decimal sUBTOTAL_AMTField;
        
        private decimal tOTAL_DISC_AMTField;
        
        private decimal tOTAL_TAXABLE_AMTField;
        
        private decimal tOTAL_TAX_AMTField;
        
        private decimal tOTAL_AMTField;
        
        private string gEOCODE_TOField;
        
        private long tAXAUTH_NOField;
        
        private long cHANGE_USERField;
        
        private System.DateTime cHANGE_DATEField;
        
        private System.Nullable<long> bILLTO_CUST_NOField;
        
        private System.Nullable<long> sERVICE_CUST_NOField;
        
        private System.Nullable<long> sITE_NOField;
        
        private System.Nullable<long> pROSPECT_NOField;
        
        private string jOBGL_IDField;
        
        private string jOBREQ_IDField;
        
        private System.Nullable<System.DateTime> qUOTED_DATEField;
        
        private System.Nullable<decimal> qUOTED_AMTField;
        
        private System.Nullable<decimal> qUOTED_TAX_AMTField;
        
        private System.Nullable<long> qUOTED_EMP_NOField;
        
        private System.Nullable<decimal> rECUR_AMTField;
        
        private System.Nullable<decimal> rECUR_TAX_AMTField;
        
        private System.Nullable<long> pPYCOL_CTRL_NOField;
        
        private System.Nullable<long> tERMS_NOField;
        
        private string iNVPRTLVL_IDField;
        
        private System.Nullable<long> cONT_NOField;
        
        private System.Nullable<System.DateTime> cOMPLETE_DATEField;
        
        private string bILL_COMMENTField;
        
        private System.Nullable<System.DateTime> sCHED_DATEField;
        
        private string pO_NUMBERField;
        
        private string eXEMPT_NOField;
        
        private System.Nullable<decimal> mIN_TIME_HOURField;
        
        private System.Nullable<decimal> mIN_CHR_AMTField;
        
        private System.Nullable<decimal> iNCR_TIME_HOURField;
        
        private System.Nullable<decimal> hOURLY_RATEField;
        
        private System.Nullable<long> iNV_FORM_NOField;
        
        private string sYSTYPE_IDField;
        
        private System.Nullable<long> sYSTEM_NOField;
        
        private string cS_NOField;
        
        private System.Nullable<long> iNCIDENT_NOField;
        
        private System.Nullable<long> iSSUE_SEQNOField;
        
        private string pROBDIAG_IDField;
        
        private string aCTUALPROB_IDField;
        
        private string pROMO_IDField;
        
        private string pACKAGE_IDField;
        
        private string jOBCAUSE_IDField;
        
        private System.Nullable<System.DateTime> cOMMIT_DATEField;
        
        private System.Nullable<int> cOMMIT_START_TIMEField;
        
        private System.Nullable<int> cOMMIT_END_TIMEField;
        
        private System.Nullable<decimal> cOLLECT_AMTField;
        
        private System.Nullable<decimal> pREPAY_AMTField;
        
        private System.Nullable<long> sCRIPT_NOField;
        
        private string cOMMNTField;
        
        private string pANEL_PHONEField;
        
        private string bACKUP_PHONEField;
        
        private System.Nullable<long> sALES_EMP_NOField;
        
        private string uDF1Field;
        
        private string uDF2Field;
        
        private string uDF3Field;
        
        private string uDF4Field;
        
        private System.Nullable<long> bRANCH_NOField;
        
        private System.Nullable<long> sALES_EMP_NO2Field;
        
        private string sERVPLAN_IDField;
        
        private string rEQ_BYField;
        
        private string rEQ_PHONEField;
        
        private string iNSPECTION_FLAGField;
        
        private System.Nullable<int> pRIORITYField;
        
        private System.Nullable<long> sALES_EMP_NO3Field;
        
        private string mONSYS_IDField;
        
        private System.Nullable<long> dISPATCH_EMP_NOField;
        
        private System.Nullable<System.DateTime> eFFECTIVE_DATEField;
        
        private System.Nullable<System.DateTime> eXPIRE_DATEField;
        
        private System.Nullable<long> rEF_JOB_NOField;
        
        private System.Nullable<long> pRCLIST_NOField;
        
        private System.Nullable<System.DateTime> eST_COMPLETE_DATEField;
        
        private System.Nullable<decimal> cOMMISSION1Field;
        
        private System.Nullable<decimal> cOMMISSION2Field;
        
        private System.Nullable<System.DateTime> cOMMISSION_DATEField;
        
        private System.Nullable<decimal> pAYBACK_RECUR_AMTField;
        
        private string mAIL_TOField;
        
        private System.Nullable<long> mAIL_NOField;
        
        private System.Nullable<System.DateTime> sTATUS_DATEField;
        
        private string tO_IN_CITY_FLAGField;
        
        private string sERVAREA_IDField;
        
        private string mBMSTAT_IDField;
        
        private System.Nullable<long> aUTH_EMP_NOField;
        
        private string aUTH_BYField;
        
        private string pREVWAGE_IDField;
        
        private string eXT_JOB_NOField;
        
        private System.Nullable<System.DateTime> eXT_CREATE_DATEField;
        
        private string jOB_NAMEField;
        
        private string jOB_ADDR1Field;
        
        private string jOB_ADDR2Field;
        
        private string cITY_NAMEField;
        
        private string sTATE_IDField;
        
        private string zIP_CODEField;
        
        private System.Nullable<System.DateTime> cOMMIT_END_DATEField;
        
        private string jOBCLASS_IDField;
        
        private System.Nullable<long> rECUR_MOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long JOB_NO
        {
            get
            {
                return this.jOB_NOField;
            }
            set
            {
                this.jOB_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CREATE_DATE
        {
            get
            {
                return this.cREATE_DATEField;
            }
            set
            {
                this.cREATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CREATE_USER
        {
            get
            {
                return this.cREATE_USERField;
            }
            set
            {
                this.cREATE_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long CO_NO
        {
            get
            {
                return this.cO_NOField;
            }
            set
            {
                this.cO_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string JOBTYPE_ID
        {
            get
            {
                return this.jOBTYPE_IDField;
            }
            set
            {
                this.jOBTYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string JOBSTAT_ID
        {
            get
            {
                return this.jOBSTAT_IDField;
            }
            set
            {
                this.jOBSTAT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string INSTALL_FLAG
        {
            get
            {
                return this.iNSTALL_FLAGField;
            }
            set
            {
                this.iNSTALL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BILL_LABOR_FLAG
        {
            get
            {
                return this.bILL_LABOR_FLAGField;
            }
            set
            {
                this.bILL_LABOR_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BILL_PARTS_FLAG
        {
            get
            {
                return this.bILL_PARTS_FLAGField;
            }
            set
            {
                this.bILL_PARTS_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BILL_TRIP_FLAG
        {
            get
            {
                return this.bILL_TRIP_FLAGField;
            }
            set
            {
                this.bILL_TRIP_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LOCAL_FLAG
        {
            get
            {
                return this.lOCAL_FLAGField;
            }
            set
            {
                this.lOCAL_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal EST_HOURS
        {
            get
            {
                return this.eST_HOURSField;
            }
            set
            {
                this.eST_HOURSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal EXTRA_EQUIP_HOURS
        {
            get
            {
                return this.eXTRA_EQUIP_HOURSField;
            }
            set
            {
                this.eXTRA_EQUIP_HOURSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal SUBTOTAL_AMT
        {
            get
            {
                return this.sUBTOTAL_AMTField;
            }
            set
            {
                this.sUBTOTAL_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal TOTAL_DISC_AMT
        {
            get
            {
                return this.tOTAL_DISC_AMTField;
            }
            set
            {
                this.tOTAL_DISC_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal TOTAL_TAXABLE_AMT
        {
            get
            {
                return this.tOTAL_TAXABLE_AMTField;
            }
            set
            {
                this.tOTAL_TAXABLE_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal TOTAL_TAX_AMT
        {
            get
            {
                return this.tOTAL_TAX_AMTField;
            }
            set
            {
                this.tOTAL_TAX_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal TOTAL_AMT
        {
            get
            {
                return this.tOTAL_AMTField;
            }
            set
            {
                this.tOTAL_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string GEOCODE_TO
        {
            get
            {
                return this.gEOCODE_TOField;
            }
            set
            {
                this.gEOCODE_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long TAXAUTH_NO
        {
            get
            {
                return this.tAXAUTH_NOField;
            }
            set
            {
                this.tAXAUTH_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public long CHANGE_USER
        {
            get
            {
                return this.cHANGE_USERField;
            }
            set
            {
                this.cHANGE_USERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime CHANGE_DATE
        {
            get
            {
                return this.cHANGE_DATEField;
            }
            set
            {
                this.cHANGE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> BILLTO_CUST_NO
        {
            get
            {
                return this.bILLTO_CUST_NOField;
            }
            set
            {
                this.bILLTO_CUST_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<long> SERVICE_CUST_NO
        {
            get
            {
                return this.sERVICE_CUST_NOField;
            }
            set
            {
                this.sERVICE_CUST_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<long> SITE_NO
        {
            get
            {
                return this.sITE_NOField;
            }
            set
            {
                this.sITE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<long> PROSPECT_NO
        {
            get
            {
                return this.pROSPECT_NOField;
            }
            set
            {
                this.pROSPECT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string JOBGL_ID
        {
            get
            {
                return this.jOBGL_IDField;
            }
            set
            {
                this.jOBGL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string JOBREQ_ID
        {
            get
            {
                return this.jOBREQ_IDField;
            }
            set
            {
                this.jOBREQ_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<System.DateTime> QUOTED_DATE
        {
            get
            {
                return this.qUOTED_DATEField;
            }
            set
            {
                this.qUOTED_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<decimal> QUOTED_AMT
        {
            get
            {
                return this.qUOTED_AMTField;
            }
            set
            {
                this.qUOTED_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<decimal> QUOTED_TAX_AMT
        {
            get
            {
                return this.qUOTED_TAX_AMTField;
            }
            set
            {
                this.qUOTED_TAX_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<long> QUOTED_EMP_NO
        {
            get
            {
                return this.qUOTED_EMP_NOField;
            }
            set
            {
                this.qUOTED_EMP_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<decimal> RECUR_AMT
        {
            get
            {
                return this.rECUR_AMTField;
            }
            set
            {
                this.rECUR_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<decimal> RECUR_TAX_AMT
        {
            get
            {
                return this.rECUR_TAX_AMTField;
            }
            set
            {
                this.rECUR_TAX_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<long> PPYCOL_CTRL_NO
        {
            get
            {
                return this.pPYCOL_CTRL_NOField;
            }
            set
            {
                this.pPYCOL_CTRL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<long> TERMS_NO
        {
            get
            {
                return this.tERMS_NOField;
            }
            set
            {
                this.tERMS_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string INVPRTLVL_ID
        {
            get
            {
                return this.iNVPRTLVL_IDField;
            }
            set
            {
                this.iNVPRTLVL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<long> CONT_NO
        {
            get
            {
                return this.cONT_NOField;
            }
            set
            {
                this.cONT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<System.DateTime> COMPLETE_DATE
        {
            get
            {
                return this.cOMPLETE_DATEField;
            }
            set
            {
                this.cOMPLETE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string BILL_COMMENT
        {
            get
            {
                return this.bILL_COMMENTField;
            }
            set
            {
                this.bILL_COMMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<System.DateTime> SCHED_DATE
        {
            get
            {
                return this.sCHED_DATEField;
            }
            set
            {
                this.sCHED_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string PO_NUMBER
        {
            get
            {
                return this.pO_NUMBERField;
            }
            set
            {
                this.pO_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string EXEMPT_NO
        {
            get
            {
                return this.eXEMPT_NOField;
            }
            set
            {
                this.eXEMPT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<decimal> MIN_TIME_HOUR
        {
            get
            {
                return this.mIN_TIME_HOURField;
            }
            set
            {
                this.mIN_TIME_HOURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<decimal> MIN_CHR_AMT
        {
            get
            {
                return this.mIN_CHR_AMTField;
            }
            set
            {
                this.mIN_CHR_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public System.Nullable<decimal> INCR_TIME_HOUR
        {
            get
            {
                return this.iNCR_TIME_HOURField;
            }
            set
            {
                this.iNCR_TIME_HOURField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public System.Nullable<decimal> HOURLY_RATE
        {
            get
            {
                return this.hOURLY_RATEField;
            }
            set
            {
                this.hOURLY_RATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public System.Nullable<long> INV_FORM_NO
        {
            get
            {
                return this.iNV_FORM_NOField;
            }
            set
            {
                this.iNV_FORM_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string SYSTYPE_ID
        {
            get
            {
                return this.sYSTYPE_IDField;
            }
            set
            {
                this.sYSTYPE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<long> SYSTEM_NO
        {
            get
            {
                return this.sYSTEM_NOField;
            }
            set
            {
                this.sYSTEM_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string CS_NO
        {
            get
            {
                return this.cS_NOField;
            }
            set
            {
                this.cS_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public System.Nullable<long> INCIDENT_NO
        {
            get
            {
                return this.iNCIDENT_NOField;
            }
            set
            {
                this.iNCIDENT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public System.Nullable<long> ISSUE_SEQNO
        {
            get
            {
                return this.iSSUE_SEQNOField;
            }
            set
            {
                this.iSSUE_SEQNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string PROBDIAG_ID
        {
            get
            {
                return this.pROBDIAG_IDField;
            }
            set
            {
                this.pROBDIAG_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string ACTUALPROB_ID
        {
            get
            {
                return this.aCTUALPROB_IDField;
            }
            set
            {
                this.aCTUALPROB_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string PROMO_ID
        {
            get
            {
                return this.pROMO_IDField;
            }
            set
            {
                this.pROMO_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string PACKAGE_ID
        {
            get
            {
                return this.pACKAGE_IDField;
            }
            set
            {
                this.pACKAGE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string JOBCAUSE_ID
        {
            get
            {
                return this.jOBCAUSE_IDField;
            }
            set
            {
                this.jOBCAUSE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=58)]
        public System.Nullable<System.DateTime> COMMIT_DATE
        {
            get
            {
                return this.cOMMIT_DATEField;
            }
            set
            {
                this.cOMMIT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=59)]
        public System.Nullable<int> COMMIT_START_TIME
        {
            get
            {
                return this.cOMMIT_START_TIMEField;
            }
            set
            {
                this.cOMMIT_START_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=60)]
        public System.Nullable<int> COMMIT_END_TIME
        {
            get
            {
                return this.cOMMIT_END_TIMEField;
            }
            set
            {
                this.cOMMIT_END_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=61)]
        public System.Nullable<decimal> COLLECT_AMT
        {
            get
            {
                return this.cOLLECT_AMTField;
            }
            set
            {
                this.cOLLECT_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=62)]
        public System.Nullable<decimal> PREPAY_AMT
        {
            get
            {
                return this.pREPAY_AMTField;
            }
            set
            {
                this.pREPAY_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=63)]
        public System.Nullable<long> SCRIPT_NO
        {
            get
            {
                return this.sCRIPT_NOField;
            }
            set
            {
                this.sCRIPT_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string COMMNT
        {
            get
            {
                return this.cOMMNTField;
            }
            set
            {
                this.cOMMNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string PANEL_PHONE
        {
            get
            {
                return this.pANEL_PHONEField;
            }
            set
            {
                this.pANEL_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string BACKUP_PHONE
        {
            get
            {
                return this.bACKUP_PHONEField;
            }
            set
            {
                this.bACKUP_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=67)]
        public System.Nullable<long> SALES_EMP_NO
        {
            get
            {
                return this.sALES_EMP_NOField;
            }
            set
            {
                this.sALES_EMP_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string UDF1
        {
            get
            {
                return this.uDF1Field;
            }
            set
            {
                this.uDF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string UDF2
        {
            get
            {
                return this.uDF2Field;
            }
            set
            {
                this.uDF2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string UDF3
        {
            get
            {
                return this.uDF3Field;
            }
            set
            {
                this.uDF3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string UDF4
        {
            get
            {
                return this.uDF4Field;
            }
            set
            {
                this.uDF4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=72)]
        public System.Nullable<long> BRANCH_NO
        {
            get
            {
                return this.bRANCH_NOField;
            }
            set
            {
                this.bRANCH_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=73)]
        public System.Nullable<long> SALES_EMP_NO2
        {
            get
            {
                return this.sALES_EMP_NO2Field;
            }
            set
            {
                this.sALES_EMP_NO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string SERVPLAN_ID
        {
            get
            {
                return this.sERVPLAN_IDField;
            }
            set
            {
                this.sERVPLAN_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string REQ_BY
        {
            get
            {
                return this.rEQ_BYField;
            }
            set
            {
                this.rEQ_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string REQ_PHONE
        {
            get
            {
                return this.rEQ_PHONEField;
            }
            set
            {
                this.rEQ_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string INSPECTION_FLAG
        {
            get
            {
                return this.iNSPECTION_FLAGField;
            }
            set
            {
                this.iNSPECTION_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=78)]
        public System.Nullable<int> PRIORITY
        {
            get
            {
                return this.pRIORITYField;
            }
            set
            {
                this.pRIORITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=79)]
        public System.Nullable<long> SALES_EMP_NO3
        {
            get
            {
                return this.sALES_EMP_NO3Field;
            }
            set
            {
                this.sALES_EMP_NO3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public string MONSYS_ID
        {
            get
            {
                return this.mONSYS_IDField;
            }
            set
            {
                this.mONSYS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=81)]
        public System.Nullable<long> DISPATCH_EMP_NO
        {
            get
            {
                return this.dISPATCH_EMP_NOField;
            }
            set
            {
                this.dISPATCH_EMP_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=82)]
        public System.Nullable<System.DateTime> EFFECTIVE_DATE
        {
            get
            {
                return this.eFFECTIVE_DATEField;
            }
            set
            {
                this.eFFECTIVE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=83)]
        public System.Nullable<System.DateTime> EXPIRE_DATE
        {
            get
            {
                return this.eXPIRE_DATEField;
            }
            set
            {
                this.eXPIRE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=84)]
        public System.Nullable<long> REF_JOB_NO
        {
            get
            {
                return this.rEF_JOB_NOField;
            }
            set
            {
                this.rEF_JOB_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=85)]
        public System.Nullable<long> PRCLIST_NO
        {
            get
            {
                return this.pRCLIST_NOField;
            }
            set
            {
                this.pRCLIST_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=86)]
        public System.Nullable<System.DateTime> EST_COMPLETE_DATE
        {
            get
            {
                return this.eST_COMPLETE_DATEField;
            }
            set
            {
                this.eST_COMPLETE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=87)]
        public System.Nullable<decimal> COMMISSION1
        {
            get
            {
                return this.cOMMISSION1Field;
            }
            set
            {
                this.cOMMISSION1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=88)]
        public System.Nullable<decimal> COMMISSION2
        {
            get
            {
                return this.cOMMISSION2Field;
            }
            set
            {
                this.cOMMISSION2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=89)]
        public System.Nullable<System.DateTime> COMMISSION_DATE
        {
            get
            {
                return this.cOMMISSION_DATEField;
            }
            set
            {
                this.cOMMISSION_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=90)]
        public System.Nullable<decimal> PAYBACK_RECUR_AMT
        {
            get
            {
                return this.pAYBACK_RECUR_AMTField;
            }
            set
            {
                this.pAYBACK_RECUR_AMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=91)]
        public string MAIL_TO
        {
            get
            {
                return this.mAIL_TOField;
            }
            set
            {
                this.mAIL_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=92)]
        public System.Nullable<long> MAIL_NO
        {
            get
            {
                return this.mAIL_NOField;
            }
            set
            {
                this.mAIL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=93)]
        public System.Nullable<System.DateTime> STATUS_DATE
        {
            get
            {
                return this.sTATUS_DATEField;
            }
            set
            {
                this.sTATUS_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=94)]
        public string TO_IN_CITY_FLAG
        {
            get
            {
                return this.tO_IN_CITY_FLAGField;
            }
            set
            {
                this.tO_IN_CITY_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=95)]
        public string SERVAREA_ID
        {
            get
            {
                return this.sERVAREA_IDField;
            }
            set
            {
                this.sERVAREA_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=96)]
        public string MBMSTAT_ID
        {
            get
            {
                return this.mBMSTAT_IDField;
            }
            set
            {
                this.mBMSTAT_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=97)]
        public System.Nullable<long> AUTH_EMP_NO
        {
            get
            {
                return this.aUTH_EMP_NOField;
            }
            set
            {
                this.aUTH_EMP_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=98)]
        public string AUTH_BY
        {
            get
            {
                return this.aUTH_BYField;
            }
            set
            {
                this.aUTH_BYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=99)]
        public string PREVWAGE_ID
        {
            get
            {
                return this.pREVWAGE_IDField;
            }
            set
            {
                this.pREVWAGE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=100)]
        public string EXT_JOB_NO
        {
            get
            {
                return this.eXT_JOB_NOField;
            }
            set
            {
                this.eXT_JOB_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=101)]
        public System.Nullable<System.DateTime> EXT_CREATE_DATE
        {
            get
            {
                return this.eXT_CREATE_DATEField;
            }
            set
            {
                this.eXT_CREATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=102)]
        public string JOB_NAME
        {
            get
            {
                return this.jOB_NAMEField;
            }
            set
            {
                this.jOB_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=103)]
        public string JOB_ADDR1
        {
            get
            {
                return this.jOB_ADDR1Field;
            }
            set
            {
                this.jOB_ADDR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=104)]
        public string JOB_ADDR2
        {
            get
            {
                return this.jOB_ADDR2Field;
            }
            set
            {
                this.jOB_ADDR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=105)]
        public string CITY_NAME
        {
            get
            {
                return this.cITY_NAMEField;
            }
            set
            {
                this.cITY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=106)]
        public string STATE_ID
        {
            get
            {
                return this.sTATE_IDField;
            }
            set
            {
                this.sTATE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=107)]
        public string ZIP_CODE
        {
            get
            {
                return this.zIP_CODEField;
            }
            set
            {
                this.zIP_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=108)]
        public System.Nullable<System.DateTime> COMMIT_END_DATE
        {
            get
            {
                return this.cOMMIT_END_DATEField;
            }
            set
            {
                this.cOMMIT_END_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=109)]
        public string JOBCLASS_ID
        {
            get
            {
                return this.jOBCLASS_IDField;
            }
            set
            {
                this.jOBCLASS_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=110)]
        public System.Nullable<long> RECUR_MOS
        {
            get
            {
                return this.rECUR_MOSField;
            }
            set
            {
                this.rECUR_MOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adt.com/MasterMind/WebService/")]
    public partial class SimpleResultOfBoolean
    {
        
        private bool errorFlagField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private bool returnValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ErrorFlag
        {
            get
            {
                return this.errorFlagField;
            }
            set
            {
                this.errorFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ReturnValue
        {
            get
            {
                return this.returnValueField;
            }
            set
            {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adt.com/MasterMind/WebService/")]
    public partial class SimpleResultOfDateTime
    {
        
        private bool errorFlagField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private System.DateTime returnValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ErrorFlag
        {
            get
            {
                return this.errorFlagField;
            }
            set
            {
                this.errorFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ReturnValue
        {
            get
            {
                return this.returnValueField;
            }
            set
            {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adt.com/MasterMind/WebService/")]
    public partial class SimpleResultOfInt64
    {
        
        private bool errorFlagField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private long returnValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ErrorFlag
        {
            get
            {
                return this.errorFlagField;
            }
            set
            {
                this.errorFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ReturnValue
        {
            get
            {
                return this.returnValueField;
            }
            set
            {
                this.returnValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface JobServiceSoapChannel : TSOpsExceptionServiceReference.JobServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class JobServiceSoapClient : System.ServiceModel.ClientBase<TSOpsExceptionServiceReference.JobServiceSoap>, TSOpsExceptionServiceReference.JobServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JobServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(JobServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), JobServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JobServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JobServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JobServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job> GetJobAsync(long Job_No)
        {
            return base.Channel.GetJobAsync(Job_No);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetJobListAsync(long[] job_NoList)
        {
            return base.Channel.GetJobListAsync(job_NoList);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetActiveJobListForSiteAsync(long site_No)
        {
            return base.Channel.GetActiveJobListForSiteAsync(site_No);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.Job[]> GetActiveJobListAsync(long[] site_NoList)
        {
            return base.Channel.GetActiveJobListAsync(site_NoList);
        }
        
        public System.Threading.Tasks.Task<long> UpdateJobAsync(TSOpsExceptionServiceReference.Job job, long emp_No)
        {
            return base.Channel.UpdateJobAsync(job, emp_No);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfInt64> CancelJobBookingAsync(long job_No, long emp_No, string recall_Id, int priority)
        {
            return base.Channel.CancelJobBookingAsync(job_No, emp_No, recall_Id, priority);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfInt64> CancelJobAsync(long job_No, long emp_No, string recall_Id, string jobCause_Id, string jobRes_Id)
        {
            return base.Channel.CancelJobAsync(job_No, emp_No, recall_Id, jobCause_Id, jobRes_Id);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfDateTime> GetJobScheduledArrivalDateAsync(long job_No)
        {
            return base.Channel.GetJobScheduledArrivalDateAsync(job_No);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfBoolean> TouchJobHeaderAsync(long jobNumber)
        {
            return base.Channel.TouchJobHeaderAsync(jobNumber);
        }
        
        public System.Threading.Tasks.Task<TSOpsExceptionServiceReference.SimpleResultOfBoolean> UpdateEstimatedHoursAsync(long jobNumber, decimal estHours)
        {
            return base.Channel.UpdateEstimatedHoursAsync(jobNumber, estHours);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JobServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.JobServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JobServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://mmbwsprod.cfsad.com:81/JobService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.JobServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://mmbwsprod.cfsad.com:81/JobService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            JobServiceSoap,
            
            JobServiceSoap12,
        }
    }
}
